//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFMergeTool.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFMergeTool.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Anyway.
        /// </summary>
        internal static string AddAnyway {
            get {
                return ResourceManager.GetString("AddAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} file(s). Note: {1} file(s) with duplicate names were added..
        /// </summary>
        internal static string AddedFilesWithDuplicates {
            get {
                return ResourceManager.GetString("AddedFilesWithDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one more PDF file to enable merging.
        /// </summary>
        internal static string AddMoreToEnable {
            get {
                return ResourceManager.GetString("AddMoreToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF files to begin.
        /// </summary>
        internal static string AddToBegin {
            get {
                return ResourceManager.GetString("AddToBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merge Tool.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        internal static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Files.
        /// </summary>
        internal static string ClearAllFiles {
            get {
                return ResourceManager.GetString("ClearAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all files?.
        /// </summary>
        internal static string ClearFilesConfirm {
            get {
                return ResourceManager.GetString("ClearFilesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop PDF Files Here.
        /// </summary>
        internal static string DragDropHere {
            get {
                return ResourceManager.GetString("DragDropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate File Name.
        /// </summary>
        internal static string DuplicateFileName {
            get {
                return ResourceManager.GetString("DuplicateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the merged PDF file:.
        /// </summary>
        internal static string EnterNameForMerged {
            get {
                return ResourceManager.GetString("EnterNameForMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName_Prompt {
            get {
                return ResourceManager.GetString("FileName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &quot;{0}&quot; already exists in the list. The files may have different content. Would you like to add it anyway?.
        /// </summary>
        internal static string FileWithSameNameExists {
            get {
                return ResourceManager.GetString("FileWithSameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload PDF files, arrange them in the desired order, then merge them into a single document..
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Complete.
        /// </summary>
        internal static string MergeComplete {
            get {
                return ResourceManager.GetString("MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge failed. Please try again..
        /// </summary>
        internal static string MergeFailed {
            get {
                return ResourceManager.GetString("MergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF merge failed: {0}.
        /// </summary>
        internal static string MergeFailedMessage {
            get {
                return ResourceManager.GetString("MergeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge PDFs.
        /// </summary>
        internal static string MergePDFs {
            get {
                return ResourceManager.GetString("MergePDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merge Successful!.
        /// </summary>
        internal static string MergeSuccessful {
            get {
                return ResourceManager.GetString("MergeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFs successfully merged as:\n{0}\n\nWould you like to open it now?.
        /// </summary>
        internal static string MergeSuccessMessage {
            get {
                return ResourceManager.GetString("MergeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging PDFs....
        /// </summary>
        internal static string MergingPDFs {
            get {
                return ResourceManager.GetString("MergingPDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to bottom.
        /// </summary>
        internal static string MoveToBottom {
            get {
                return ResourceManager.GetString("MoveToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        internal static string MoveToTop {
            get {
                return ResourceManager.GetString("MoveToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least two PDF files to merge..
        /// </summary>
        internal static string NeedTwoFiles {
            get {
                return ResourceManager.GetString("NeedTwoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PDF files added yet.
        /// </summary>
        internal static string NoFilesYet {
            get {
                return ResourceManager.GetString("NoFilesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Files.
        /// </summary>
        internal static string NotEnoughFiles {
            get {
                return ResourceManager.GetString("NotEnoughFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid PDF file..
        /// </summary>
        internal static string NotValidPDF {
            get {
                return ResourceManager.GetString("NotValidPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or use the Upload button above.
        /// </summary>
        internal static string OrUseUpload {
            get {
                return ResourceManager.GetString("OrUseUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Location.
        /// </summary>
        internal static string OutputLocation {
            get {
                return ResourceManager.GetString("OutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to merge....
        /// </summary>
        internal static string PreparingToMerge {
            get {
                return ResourceManager.GetString("PreparingToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview PDF.
        /// </summary>
        internal static string PreviewPDF {
            get {
                return ResourceManager.GetString("PreviewPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to merge {0} PDF files.
        /// </summary>
        internal static string ReadyToMerge {
            get {
                return ResourceManager.GetString("ReadyToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        internal static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        internal static string RemoveFileConfirm {
            get {
                return ResourceManager.GetString("RemoveFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Would you like to replace it?.
        /// </summary>
        internal static string ReplaceQuestion {
            get {
                return ResourceManager.GetString("ReplaceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload PDF Files.
        /// </summary>
        internal static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload or drag files to get started.
        /// </summary>
        internal static string UploadToStart {
            get {
                return ResourceManager.GetString("UploadToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default.
        /// </summary>
        internal static string UseDefault {
            get {
                return ResourceManager.GetString("UseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you like to save the merged PDF?.
        /// </summary>
        internal static string WhereToSave {
            get {
                return ResourceManager.GetString("WhereToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
